---

- name: "{{ method }} {{ act_service }} declaration"
  uri:
    url: "https://{{ provider.server }}{{ actUrl }}"
    method: "{{ method }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    return_content: true
    validate_certs: false
    body_format: json
    body: "{{ lookup('file', declaration) }}"
    status_code: 202, 200
  register: result
  delegate_to: localhost
  changed_when: "'success' in result.json.results | map(attribute='message')"
  
- name: Print Returned Declaration
  debug:
      msg: "{{ result.json.declaration }}"
  when: method == 'POST'